export const Actiontypes = {
  SET_USER: "SET_USER",
  SET_CURRENT_USER: "SET_CURRENT_USER",
  UNSET_CURRENT_USER: "UNSET_CURRENT_USER",
  SET_STAGE: "SET_STAGE",
  CHANGE_STAGE: "CHANGE_STAGE",
  SET_CARD: "SET_CARD",
  CHANGE_CARD: "CHANGE_CARD",
};
